'use client';

import React from 'react';
import Image from 'next/image';
import { SignInButton, SignUpButton } from '@clerk/nextjs';
import styles from '@/styles/HomePage.module.css';

export function LandingPage() {
  return (
    <div className={styles.container}>
      {/* Header */}
      <header className={styles.header}>
        <div className={styles.headerContent}>
          <div className={styles.logo}>
            <Image 
              src="/images/ohm-icon.svg" 
              alt="Ohm" 
              width={40} 
              height={40}
            />
            <h1>Ohm</h1>
          </div>
          <div className={styles.authButtons}>
            <SignInButton mode="modal">
              <button className={styles.signInButton}>
                Sign In
              </button>
            </SignInButton>
            <SignUpButton mode="modal">
              <button className={styles.signUpButton}>
                Sign Up
              </button>
            </SignUpButton>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className={styles.heroSection}>
        <div className={styles.heroContent}>
          <div className={styles.heroText}>
            <h1 className={styles.heroTitle}>
              AI-First Video
              <span className={styles.gradientText}> Conferencing</span>
            </h1>
            <p className={styles.heroSubtitle}>
              Smart meetings with real-time transcription, personalized notes, 
              and AI-powered insights. Transform how your team collaborates.
            </p>
            <div className={styles.heroActions}>
              <SignUpButton mode="modal">
                <button className={styles.primaryButton}>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
                    <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="2"/>
                    <polygon points="10,8 16,12 10,16" fill="currentColor"/>
                  </svg>
                  Get Started
                </button>
              </SignUpButton>
              <button className={styles.secondaryButton}>
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
                  <polygon points="5,3 19,12 5,21" fill="currentColor"/>
                </svg>
                Watch Demo
              </button>
            </div>
          </div>
          <div className={styles.heroVisual}>
            <div className={styles.floatingCard}>
              <div className={styles.cardHeader}>
                <div className={styles.cardDots}>
                  <span></span>
                  <span></span>
                  <span></span>
                </div>
                <span className={styles.cardTitle}>Live Meeting</span>
              </div>
              <div className={styles.cardContent}>
                <div className={styles.mockTranscript}>
                  <div className={styles.transcriptLine}>
                    <span className={styles.speaker}>Alex:</span>
                    <span>Let&apos;s discuss the Q4 roadmap...</span>
                  </div>
                  <div className={styles.transcriptLine}>
                    <span className={styles.speaker}>Sarah:</span>
                    <span>I think we should prioritize the AI features</span>
                  </div>
                </div>
                <div className={styles.aiSummary}>
                  <div className={styles.aiIcon}>🤖</div>
                  <span>AI generating summary...</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className={styles.featuresSection}>
        <div className={styles.featuresContent}>
          <h2 className={styles.featuresTitle}>Why Choose Ohm?</h2>
          <div className={styles.featuresGrid}>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🤖</div>
              <h3>AI-Powered Insights</h3>
              <p>Get intelligent summaries, action items, and meeting insights automatically generated by AI.</p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>📝</div>
              <h3>Real-time Transcription</h3>
              <p>Never miss a word with accurate, real-time transcription and speaker identification.</p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🏠</div>
              <h3>Persistent Meeting Rooms</h3>
              <p>Create dedicated spaces for your teams with shared context and task management.</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
} 